### PR TITLE
Setup/azure static webapp

### PR DESCRIPTION
**Pull request by Howllo**
I forgot the na in name, woops.

### CODE REVIEW

**Comment by soot0-JoshR** [comment]
@Howllo It looks like its missing deployment_token

**Comment by Howllo** [comment]
@soot0-JoshR  You cannot get the deployment token until the Static App is setup since it is a secret and it will automatically install once it able to run that app.

**Comment by soot0-JoshR** [comment]
@Howllo Isn't deployment_token you need in azure? I must be misunderstanding something, the failed check seems like a catch-22. Can you deploy manually?

**Comment by Howllo** [comment]
@soot0-JoshR Because of this error:

Request to GitHub (PUT https://api.github.com/repos/Devature/penguin-client/contents/.github/workflows/azure-static-web-apps-brave-hill-0b347711e.yml) failed with status code: 409 (Conflict). Error details from GitHub: {"message":"Repository rule violations found\n\nChanges must be made through a pull request.\n\n","metadata":{},"documentation_url":"https://docs.github.com/rest/repos/contents#create-or-update-file-contents","status":"409"}. Click here for details

**Comment by soot0-JoshR** [comment]
@Howllo The failed check won't prevent merging?

**Review by soot0-JoshR — APPROVED** [review]
Looks good. It seems like the failed check on the static web app deployment would prevent merging, but we'll see :)

**Pull request merged**
